a = str("This is string")
b = int(20)
c = float(20.5)
d = complex(11j)
e = list(("apple", "banana", "cherry"))
f = tuple(("apple", "banana", "cherry"))
g = range(6)
h = dict(name="John", age=36)
i = set(("apple", "banana", "cherry"))
j = frozenset(("apple", "banana", "cherry"))
k = bool(1)
l = bytes(5)
m = bytearray(5)
n = memoryview(bytes(5))
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)
print(m)
print(n)
