txt = "String Method in Python"
print(txt.capitalize())
print(txt.casefold())
print(txt.center(100))
print(txt.count("Python"))
print(txt.encode())
print(txt.endswith("Python"))
print(txt.expandtabs())
print(txt.find("Python"))
print(txt.format())
#print(txt.format_map())
print(txt.index("Python"))
print(txt.isalnum())
print(txt.isalpha())
print(txt.isascii())
print(txt.isdecimal())
print(txt.isdigit())
print(txt.isidentifier())
print(txt.islower())
print(txt.isnumeric())
print(txt.isprintable())
print(txt.isspace())
print(txt.istitle())
print(txt.isupper())
print(txt.join("Python"))
print(txt.ljust(100))
print(txt.lower())
print(txt.lstrip())
print(txt.partition("Python"))
print(txt.replace("Python", "Java"))
print(txt.rfind("Python"))
print(txt.rindex("Python"))
print(txt.rjust(100))
print(txt.rpartition("Python"))
print(txt.rsplit())
print(txt.rstrip())
print(txt.split())
print(txt.splitlines())
print(txt.startswith("String"))
print(txt.strip())
print(txt.swapcase())
print(txt.title())
print(txt.upper())
print(txt.zfill(100))
print("String Method in Python".isalnum())
print("String Method in Python".casefold())
print("String Method in Python".capitalize())
print("String Method in Python".center(100))
print("String Method in Python".count("Python"))
print("String Method in Python".encode())
print("String Method in Python".endswith("Python"))
print("String Method in Python".expandtabs())
print("String Method in Python".find("Python"))
print("String Method in Python".format())
# print("String Method in Python".format_map())
print("String Method in Python".index("Python"))